export const exelliusFeatures = [
  "Email Finder",
  "Mobile Finder",
  "Email Verifier",
  "Domain Search",
  "API Access",
  "Bulk Processing",
  "Priority Support",
];

export const exelliusPlans = [
  {
    key: "free",
    name: "Free",
    monthly_price: 0,
    annual_price: 0,
    credits: 75,
    color: "bg-white",
    features: [
      "Email Finder",
      "Mobile Finder",
      "Email Verifier",
      "Domain Search",
      "API Access",
    ],
  },
  {
    key: "basic",
    name: "Basic",
    monthly_price: 59,
    annual_price: 531,
    credits: 6000,
    color: "bg-[#f4f8ff]",
    features: [
      "Email Finder",
      "Mobile Finder",
      "Email Verifier",
      "Domain Search",
      "API Access",
      "Bulk Processing",
    ],
  },
  {
    key: "growth",
    name: "Growth",
    monthly_price: 119,
    annual_price: 1068,
    credits: 13000,
    color: "bg-[#fef4f1]",
    features: [
      "Email Finder",
      "Mobile Finder",
      "Email Verifier",
      "Domain Search",
      "API Access",
      "Bulk Processing",
      "Priority Support",
    ],
  },
  {
    key: "professional",
    name: "Professional",
    monthly_price: 199,
    annual_price: 1788,
    credits: 21000,
    color: "bg-[#f8f5ff]",
    features: [
      "Email Finder",
      "Mobile Finder",
      "Email Verifier",
      "Domain Search",
      "API Access",
      "Bulk Processing",
      "Priority Support",
    ],
  },
];
